version: '3'
services:
    opi_dragon_api:
        restart: always
        build:
            context: .
        ports:
            - "8000:8000"
        env_file: .env
        networks:
            - sanic

networks:
    sanic:
